import { createClient } from '@supabase/supabase-js'
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZHBoZXlub25ha2p0d3Rrcm5lIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTE4Mzk5MywiZXhwIjoyMDcwNzU5OTkzfQ.WNV12DcZKio9hwVS_J0PqSWcA3h1rZ8IgzMfLkjlqiQ'
export const supabase = createClient(supabaseUrl, supabaseKey)